enum EErrorCode {
  CDN_EXHAUSTED = 'CDN_EXHAUSTED',
  CONTENT_PROTECTION_NOT_FOUND = 'CONTENT_PROTECTION_NOT_FOUND',
  CREATE_MEDIA_KEYS = 'CREATE_MEDIA_KEYS',
  INITIALIZE_KEY_SESSION = 'INITIALIZE_KEY_SESSION',
  INTERNAL = 'INTERNAL',
  JS_OVERFLOW = 'JS_OVERFLOW',
  LICENSE_REQUEST_FAILED = 'LICENSE_REQUEST_FAILED',
  MANIFEST_NOT_SUPPORTED = 'MANIFEST_NOT_SUPPORTED',
  MEDIA_KEY_SESSION_UPDATE = 'MEDIA_KEY_SESSION_UPDATE',
  MEDIA_SOURCE_EXTENSIONS_NOT_SUPPORTED = 'MEDIA_SOURCE_EXTENSIONS_NOT_SUPPORTED',
  MIME_TYPE_OR_CODEC_NOT_SUPPORTED = 'MIME_TYPE_OR_CODEC_NOT_SUPPORTED',
  PARSER = 'PARSER',
  READER_OUT_OF_BOUNDS = 'READER_OUT_OF_BOUNDS',
  REQUEST_MEDIA_KEY_ACCESS = 'REQUEST_MEDIA_KEY_ACCESS',
  TEXT_DECODER = 'TEXT_DECODER',
  TEXT_TRACK_NOT_SUPPORTED = 'TEXT_TRACK_NOT_SUPPORTED',
  XHR_ABORT = 'XHR_ABORT',
  XHR_LOAD = 'XHR_LOAD',
  XHR_NETWORK = 'XHR_NETWORK',
  XHR_RETRY = 'XHR_RETRY',
  XHR_TIMEOUT = 'XHR_TIMEOUT',
  XHR_UNKNOWN = 'XHR_UNKNOWN'
}

export default EErrorCode;
